### ISSUE TITLE
Can I consume you public API?

### ISSUE THREAD

**Issue by visortelle** [serokell/hackage-search#25]
Hello! 

I created a browser extension that allows search over Hoogle and Hackage.

https://user-images.githubusercontent.com/9302460/149509279-ea910d5a-8f65-43b1-ac2a-24a6f4971aba.mov

Installation instructions here: https://github.com/visortelle/hackage-ui/issues/2#issuecomment-1012527086

@bodigrim told me that "hackage-search" integration would be useful.

The question is - can I consume the public API or deploying my own instance would be preferable?

Thank you.

**Comment by int-index** [comment]
Hi, there are no stability guarantees for the API. For example, there used to be a JSON endpoint, but now we do server-side rendering and return the results as HTML.

So if you don't want to risk the extension breaking without warning, it's better to spin up a dedicated instance.

Alternatively, I could bring back the JSON API and make it stable (and JSON is probably easier to deal with, since you have more control over rendering), but it would be great to include some acknowledgement at the top of the search results that the services are provided by Serokell (it can be in really small letters and non-distracting).

**Comment by int-index** [comment]
> now we do server-side rendering and return the results as HTML

Actually, looking at the code, seems I haven't done that. But I might! 😈

**Comment by visortelle** [comment]
> > now we do server-side rendering and return the results as HTML
> 
> Actually, looking at the code, seems I haven't done that. But I might! 😈

Then I’ll consume your instance.

> it would be great to include some acknowledgement at the top of the search results that the services are provided by Serokell (it can be in really small letters and non-distracting).

Of course. 🙂
